import sys
from threading import Thread
from PyQt5 import QtCore, QtGui, QtWidgets
from ui.MainScreenController import InitProcesses
from ui import SettingsDialog, CreditsDialog, ProcessingDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(422, 404)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/logo/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(236, 234, 231);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(-10, -10, 451, 131))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("assets/logo/Logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.logo_line = QtWidgets.QFrame(self.centralwidget)
        self.logo_line.setGeometry(QtCore.QRect(-10, 100, 611, 20))
        self.logo_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.logo_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.logo_line.setObjectName("logo_line")
        self.source_folder_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.source_folder_groupBox.setGeometry(QtCore.QRect(40, 130, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.source_folder_groupBox.setFont(font)
        self.source_folder_groupBox.setObjectName("source_folder_groupBox")
        self.source_folder_path_lineEdit = QtWidgets.QLineEdit(self.source_folder_groupBox)
        self.source_folder_path_lineEdit.setGeometry(QtCore.QRect(0, 20, 281, 21))
        self.source_folder_path_lineEdit.setObjectName("source_folder_path_lineEdit")
        self.source_folder_path_pushButton = QtWidgets.QPushButton(self.source_folder_groupBox)
        self.source_folder_path_pushButton.setGeometry(QtCore.QRect(280, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(9)
        self.source_folder_path_pushButton.setFont(font)
        self.source_folder_path_pushButton.setObjectName("source_folder_path_pushButton")
        self.source_folder_path_pushButton.clicked.connect(self.SelectSourceFolder)
        self.destination_folder_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.destination_folder_groupBox.setGeometry(QtCore.QRect(40, 180, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.destination_folder_groupBox.setFont(font)
        self.destination_folder_groupBox.setObjectName("destination_folder_groupBox")
        self.destination_folder_lineEdit = QtWidgets.QLineEdit(self.destination_folder_groupBox)
        self.destination_folder_lineEdit.setGeometry(QtCore.QRect(0, 20, 281, 21))
        self.destination_folder_lineEdit.setObjectName("destination_folder_lineEdit")
        self.destination_folder_pushButton = QtWidgets.QPushButton(self.destination_folder_groupBox)
        self.destination_folder_pushButton.setGeometry(QtCore.QRect(280, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(9)
        self.destination_folder_pushButton.setFont(font)
        self.destination_folder_pushButton.setObjectName("destination_folder_pushButton")
        self.destination_folder_pushButton.clicked.connect(self.SelectDestinationFolder)
        self.name_list_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.name_list_groupBox.setGeometry(QtCore.QRect(40, 230, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.name_list_groupBox.setFont(font)
        self.name_list_groupBox.setObjectName("name_list_groupBox")
        self.name_list_lineEdit = QtWidgets.QLineEdit(self.name_list_groupBox)
        self.name_list_lineEdit.setGeometry(QtCore.QRect(0, 20, 281, 21))
        self.name_list_lineEdit.setObjectName("name_list_lineEdit")
        self.name_list_pushButton = QtWidgets.QPushButton(self.name_list_groupBox)
        self.name_list_pushButton.setGeometry(QtCore.QRect(280, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(9)
        self.name_list_pushButton.setFont(font)
        self.name_list_pushButton.setObjectName("name_list_pushButton")
        self.name_list_pushButton.clicked.connect(self.SelectNameListFile)
        self.courses_list_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.courses_list_groupBox.setGeometry(QtCore.QRect(40, 280, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.courses_list_groupBox.setFont(font)
        self.courses_list_groupBox.setObjectName("courses_list_groupBox")
        self.courses_list_lineEdit = QtWidgets.QLineEdit(self.courses_list_groupBox)
        self.courses_list_lineEdit.setGeometry(QtCore.QRect(0, 20, 281, 21))
        self.courses_list_lineEdit.setObjectName("courses_list_lineEdit")
        self.courses_list_pushButton = QtWidgets.QPushButton(self.courses_list_groupBox)
        self.courses_list_pushButton.setGeometry(QtCore.QRect(280, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(9)
        self.courses_list_pushButton.setFont(font)
        self.courses_list_pushButton.setObjectName("courses_list_pushButton")
        self.courses_list_pushButton.clicked.connect(self.SelectCourseListFile)
        self.process_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.process_pushButton.setGeometry(QtCore.QRect(160, 340, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.process_pushButton.setFont(font)
        self.process_pushButton.setObjectName("process_pushButton")
        self.process_pushButton.clicked.connect(self.OnProcessButtonClick)
        self.settings_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.settings_pushButton.setGeometry(QtCore.QRect(380, 360, 31, 31))
        self.settings_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/misc/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_pushButton.setIcon(icon1)
        self.settings_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.settings_pushButton.setObjectName("settings_pushButton")
        self.settings_pushButton.clicked.connect(SettingsDialog.Start)
        self.credits_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.credits_pushButton.setGeometry(QtCore.QRect(10, 360, 31, 31))
        self.credits_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/misc/copyleft.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.credits_pushButton.setIcon(icon2)
        self.credits_pushButton.setIconSize(QtCore.QSize(28, 28))
        self.credits_pushButton.setObjectName("credits_pushButton")
        self.credits_pushButton.clicked.connect(CreditsDialog.Start)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ScoreSheets"))
        self.source_folder_groupBox.setTitle(_translate("MainWindow", "Certificates PDF Folder"))
        self.source_folder_path_pushButton.setText(_translate("MainWindow", "Browse"))
        self.destination_folder_groupBox.setTitle(_translate("MainWindow", "Output Folder"))
        self.destination_folder_pushButton.setText(_translate("MainWindow", "Browse"))
        self.name_list_groupBox.setTitle(_translate("MainWindow", "Names List CSV File"))
        self.name_list_pushButton.setText(_translate("MainWindow", "Browse"))
        self.courses_list_groupBox.setTitle(_translate("MainWindow", "Courses List CSV File"))
        self.courses_list_pushButton.setText(_translate("MainWindow", "Browse"))
        self.process_pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:400;\">Perform Score Calculation</span></p></body></html>"))
        self.process_pushButton.setText(_translate("MainWindow", "Calculate"))
        self.settings_pushButton.setToolTip(_translate("MainWindow", "Settings"))
        self.credits_pushButton.setToolTip(_translate("MainWindow", "Credits"))

    def SelectSourceFolder(self):
        sourceFolderPath = QtWidgets.QFileDialog.getExistingDirectory()
        self.source_folder_path_lineEdit.setText(sourceFolderPath)

    def SelectDestinationFolder(self):
        destinationFolderPath = QtWidgets.QFileDialog.getExistingDirectory()
        self.destination_folder_lineEdit.setText(destinationFolderPath)

    def SelectNameListFile(self):
        nameListFilePath = QtWidgets.QFileDialog.getOpenFileName()
        self.name_list_lineEdit.setText(nameListFilePath[0])

    def SelectCourseListFile(self):
        courseListFilePath = QtWidgets.QFileDialog.getOpenFileName()
        self.courses_list_lineEdit.setText(courseListFilePath[0])

    def OnProcessButtonClick(self):
        # Getting Parameters
        sourceFolderPath = self.source_folder_path_lineEdit.text
        courseProviderNameListCsvFilePath = self.courses_list_lineEdit.text
        personNameListCsvFilePath = self.name_list_lineEdit.text
        isMarksCustomized = False
        outputFolderParentPath = self.destination_folder_lineEdit.text

        # InitProcesses Thread
        InitProcesses_Thread = Thread(target = InitProcesses, name = 'InitProcessesThread - MainScreen', args = (sourceFolderPath, courseProviderNameListCsvFilePath, personNameListCsvFilePath, isMarksCustomized, outputFolderParentPath))
        InitProcesses_Thread.start()
        InitProcesses_Thread.join()

        ProcessingDialog.Start()

def Start():
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec_()