import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setFixedSize(451, 346)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../assets/misc/Gear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: rgb(236, 234, 231);")
        self.logo_label = QtWidgets.QLabel(Form)
        self.logo_label.setGeometry(QtCore.QRect(140, 10, 31, 31))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("../assets/misc/Gear-icon.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.title_label = QtWidgets.QLabel(Form)
        self.title_label.setGeometry(QtCore.QRect(170, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.title_line = QtWidgets.QFrame(Form)
        self.title_line.setGeometry(QtCore.QRect(160, 40, 141, 20))
        self.title_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.title_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.title_line.setObjectName("title_line")
        self.apply_pushButton = QtWidgets.QPushButton(Form)
        self.apply_pushButton.setGeometry(QtCore.QRect(130, 300, 89, 25))
        self.apply_pushButton.setObjectName("apply_pushButton")
        self.close_pushButton = QtWidgets.QPushButton(Form)
        self.close_pushButton.setGeometry(QtCore.QRect(240, 300, 89, 25))
        self.close_pushButton.setObjectName("close_pushButton")
        self.threadcount_label = QtWidgets.QLabel(Form)
        self.threadcount_label.setGeometry(QtCore.QRect(50, 70, 241, 17))
        self.threadcount_label.setObjectName("threadcount_label")
        self.noofthreads_lineEdit = QtWidgets.QLineEdit(Form)
        self.noofthreads_lineEdit.setGeometry(QtCore.QRect(300, 70, 21, 20))
        self.noofthreads_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.noofthreads_lineEdit.setText("")
        self.noofthreads_lineEdit.setObjectName("noofthreads_lineEdit")
        self.threadnoun_label = QtWidgets.QLabel(Form)
        self.threadnoun_label.setGeometry(QtCore.QRect(330, 70, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threadnoun_label.setFont(font)
        self.threadnoun_label.setObjectName("threadnoun_label")
        self.outputfile_label = QtWidgets.QLabel(Form)
        self.outputfile_label.setGeometry(QtCore.QRect(60, 100, 161, 17))
        self.outputfile_label.setObjectName("outputfile_label")
        self.outputfilename_lineEdit = QtWidgets.QLineEdit(Form)
        self.outputfilename_lineEdit.setGeometry(QtCore.QRect(230, 100, 161, 20))
        self.outputfilename_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.outputfilename_lineEdit.setObjectName("outputfilename_lineEdit")
        self.devmsgimg_label = QtWidgets.QLabel(Form)
        self.devmsgimg_label.setGeometry(QtCore.QRect(110, 220, 241, 61))
        self.devmsgimg_label.setText("")
        self.devmsgimg_label.setPixmap(QtGui.QPixmap("../assets/misc/experimental.png"))
        self.devmsgimg_label.setScaledContents(True)
        self.devmsgimg_label.setObjectName("devmsgimg_label")
        self.devmsg_label = QtWidgets.QLabel(Form)
        self.devmsg_label.setGeometry(QtCore.QRect(70, 170, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.devmsg_label.setFont(font)
        self.devmsg_label.setStyleSheet("color: rgb(237, 51, 59);")
        self.devmsg_label.setObjectName("devmsg_label")
        self.devmsg2_label = QtWidgets.QLabel(Form)
        self.devmsg2_label.setGeometry(QtCore.QRect(100, 190, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Mono")
        font.setBold(True)
        font.setWeight(75)
        self.devmsg2_label.setFont(font)
        self.devmsg2_label.setStyleSheet("color: rgb(237, 51, 59);")
        self.devmsg2_label.setObjectName("devmsg2_label")
        self.markingschemefile_lineEdit = QtWidgets.QLineEdit(Form)
        self.markingschemefile_lineEdit.setGeometry(QtCore.QRect(230, 130, 161, 20))
        self.markingschemefile_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.markingschemefile_lineEdit.setObjectName("markingschemefile_lineEdit")
        self.markingschemefile_label = QtWidgets.QLabel(Form)
        self.markingschemefile_label.setGeometry(QtCore.QRect(50, 130, 171, 17))
        self.markingschemefile_label.setObjectName("markingschemefile_label")
        self.browse_pushButton = QtWidgets.QPushButton(Form)
        self.browse_pushButton.setGeometry(QtCore.QRect(400, 130, 21, 21))
        self.browse_pushButton.setObjectName("browse_pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Settings"))
        self.title_label.setText(_translate("Form", "Configuration"))
        self.apply_pushButton.setText(_translate("Form", "Apply"))
        self.close_pushButton.setText(_translate("Form", "Close"))
        self.threadcount_label.setText(_translate("Form", "No. of Threads for PDF Extraction : "))
        self.threadnoun_label.setText(_translate("Form", "Threads"))
        self.outputfile_label.setText(_translate("Form", "Output CSV File Name :"))
        self.devmsg_label.setText(_translate("Form", "*** These features are under development"))
        self.devmsg2_label.setText(_translate("Form", "and are currently experimental ***"))
        self.markingschemefile_label.setText(_translate("Form", "Making Scheme CSV File :"))
        self.browse_pushButton.setToolTip(_translate("Form", "Browse"))
        self.browse_pushButton.setText(_translate("Form", "..."))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())